<a href="https://colab.research.google.com/github/abhilash-1204/ABHILASH_22_001/blob/main/PRACTICE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for var in "ABHILASH":
  if var=="I":
    continue
  print(var)


A
B
H
L
A
S
H


In [ ]:
for i in range(10):
  print(i)
  if i==2:
    break

0
1
2


In [ ]:
x=abs(-7.25)
print(x)


7.25


In [ ]:
list=[0,2,2]
a=all(list)
print(a)

False


In [ ]:
tuple=(0,1,False)
a=any(tuple)
print(a)

True


In [ ]:
a=ascii("Mostly Sane")
print(a)

'Mostly Sane'


In [ ]:
a=bin(30)
print(a)

0b11110


In [ ]:
a=bool(22)
print(a)

True


In [ ]:
a=bytearray(22)
print(a)

bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')


In [ ]:
b=5
print(callable(a))

False


In [ ]:
a=chr(87)
print(a)

W


In [ ]:
a=compile('print(45)','test','eval')
exec(a)

45


In [ ]:
a=complex(2,7)
print(a)

(2+7j)


In [ ]:
a=dict(name="jaydon",mob=182182922,country="canada")
print(a)

{'name': 'jaydon', 'mob': 182182922, 'country': 'canada'}


In [ ]:
class User:
 name="jaydon"
 mob=182182922
 country="canada"
print(dir(User))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'country', 'mob', 'name']


In [ ]:
# User defined function
def show():
  print('HELLO CSE')


show()

HELLO CSE


In [ ]:
# Passing parameters in User defined function
def ADD(a,b):
  c=a+b
  print('SUM OF TWO NOS=',c)
ADD(10,20)

SUM OF TWO NOS= 30


In [ ]:
# Passing parameters in User defined function using KEYBOARD
def ADD(a,b):
  c=a+b
  print('SUM OF TWO NOS=',c)
p=int(input("Enter 1st no="))
q=int(input("Enter 2nd no="))
ADD(p,q)

Enter 1st no=5
Enter 2nd no=62
SUM OF TWO NOS= 67


In [ ]:
# Using return statement in User Defined Function
def sumofn(n):
  s=0
  for i in range(1,n+1):
     s=s+i
  return(s)
m=int(input("Enter n value="))
print('Sum of n=',sumofn(m))


Enter n value=5
Sum of n= 15


In [ ]:
p=int(input("enter the no of rows"))
num=1
for i in range(1,p+1):
    row_values=[num*(2**j) for j in range(i)]
    print(" ".join(map(str,row_values)))
    num *= i+1


enter the no of rows5
1
2 4
6 12 24
24 48 96 192
120 240 480 960 1920


In [ ]:
p=int(input("enter no of rows"))
c=1
for i in range(p+1):
  for j in range(1,i+1):
    print(c,end=" ")
    c=c+1
  print()

enter no of rows5

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


In [ ]:
list=['p','y','t','h','o','n']
print(list)

['p', 'y', 't', 'h', 'o', 'n']


In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[2:6])

[30, 40, 50, 60]


In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[:4])

[10, 20, 30, 40]


In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[4:])

[50, 60, 70, 80, 90]


In [ ]:
list=["orange","apple","potato","tomato"]
print(list)
print(len(list))

['orange', 'apple', 'potato', 'tomato']
4


In [ ]:
list1=["orange","apple","potato"]
list2=[10,20,30]
list3=[True,False,True]
print(list1)
print(list2)
print(list3)

['orange', 'apple', 'potato']
[10, 20, 30]
[True, False, True]


In [ ]:
list=['ABHILASH',1,9.0,True]
print(list[-1])

True


In [ ]:
list=['abhilash','dinasour','monster']
if 'dinasour' in list:
  print("item in the list:",list[1])

item in the list: dinasour


In [ ]:
list=['abhi','lash','mohanty']
list[2]='boss'
print(list)

['abhi', 'lash', 'boss']


In [ ]:
list=['abhi','lash','mohanty']
list.insert(1,'monster')
print(list)

['abhi', 'monster', 'lash', 'mohanty']


In [ ]:
list=['abhi','lash','mohanty']
list.append('rocky')
print(list)

['abhi', 'lash', 'mohanty', 'rocky']


In [ ]:
list1=['abhi','lash','mohanty']
list2=['boss','dunki','salaar']
list1.extend(list2)
print(list1)

['abhi', 'lash', 'mohanty', 'boss', 'dunki', 'salaar']


In [ ]:
list1=['abhi','lash','mohanty']
list1.remove('lash')
print(list1)

['abhi', 'mohanty']


In [ ]:
list=[3,5,2,7,6]
list.pop(3)
print(list)

[3, 5, 2, 6]


In [ ]:
list=[3,5,2,7,6]
del list[3]
print(list)

[3, 5, 2, 6]


In [ ]:
list=[3,5,2,7,6]
list.clear()
print(list)

[]


In [ ]:
list=[3,5,2,7,6]
for i in list:
     print(i)

3
5
2
7
6


In [ ]:
list=[3,5,2,7,6]
i=0
while(i<len(list)):
     print(list[i])
     i=i+1

3
5
2
7
6


In [ ]:
num=int(input('Enter the number:'))
def factorial(x):
    if x==0:
       return 1
    else:
       return(x*factorial(x-1))
factorial(num)
print("The factorial of",num,"is",factorial(num))


Enter the number:5
The factorial of 5 is 120


In [ ]:
import math
pie=math.pi
print("The value of pi is:",pie)

The value of pi is: 3.141592653589793


In [ ]:
import random
for i in range(10):
  print(random.randint(1,25))

3
17
20
9
4
17
13
23
1
11


In [ ]:
import random
import math
for i in range(5):
  print(random.randint(1,25))
print(math.pi)

13
16
16
14
25
3.141592653589793


In [ ]:
import math as m
print(m.pi)
print(m.e)

3.141592653589793
2.718281828459045


In [ ]:
from math import pow
print(pow(2,5))

32.0


In [ ]:
list1=['I','LOVE','PYTHON','ABIT']
list2=[1,2,3,4,5]
list3=['Python',20,54.6,'Rajiv','a','b']
list1
list2
list3

['Python', 20, 54.6, 'Rajiv', 'a', 'b']

In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[::])
print(list[::2])
print(list[1::3])
print(list[2:4:2])

[10, 20, 30, 40, 50, 60, 70, 80, 90]
[10, 30, 50, 70, 90]
[20, 50, 80]
[30]


In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[-3::])
print(list[1:-1])
print(list[-5:-2])
print(list[-3:])
print(list[1:-3:2])
print(list[:7:-2])
print(list[::-1])

[70, 80, 90]
[20, 30, 40, 50, 60, 70, 80]
[50, 60, 70]
[70, 80, 90]
[20, 40, 60]
[90]
[90, 80, 70, 60, 50, 40, 30, 20, 10]


In [ ]:
list=[10,21,30,45,50,63,78,80,90]
list[0]=1
print(list)
list[1:4]=[2,3,4]
print(list)
list[2]='Rajiv'
print(list)
list[3:5]='abc'
print(list)

[1, 21, 30, 45, 50, 63, 78, 80, 90]
[1, 2, 3, 4, 50, 63, 78, 80, 90]
[1, 2, 'Rajiv', 4, 50, 63, 78, 80, 90]
[1, 2, 'Rajiv', 'a', 'b', 'c', 63, 78, 80, 90]


In [ ]:
list=[10,21,30,45,50,63,78,80,90]
del list[0]
print(list)
del list[1:4]
print(list)
del list[::3]
print(list)

[21, 30, 45, 50, 63, 78, 80, 90]
[21, 63, 78, 80, 90]
[63, 78, 90]


In [ ]:
list1=[1,2,3,4,5]
print(list1*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,0]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [ ]:
list=[1,2,3,4]
for i in list:
  print(i)

1
2
3
4


In [ ]:
unsorted_list={5,2,3,7,99,33,71,57}
sorted_list=sorted(unsorted_list)
print("sorted_list:",sorted_list)

sorted_list: [2, 3, 5, 7, 33, 57, 71, 99]
sorted_list: [2, 3, 5, 7, 33, 57, 71, 99]


In [ ]:
a=[5,3,2,7,99,17,84]
for i in range(len(a)):
  for j in range(len(a)-1):
    if a[j]>a[j+1]:
      a[j+1],a[j]=a[j],a[j+1]

print(a)

[2, 3, 5, 7, 17, 84, 99]


In [ ]:
import numpy as np
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [ ]:
import numpy as np
data2=[[1,2,3,4],[5,6,7,8],[55,66,76,88]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [55 66 76 88]]


In [ ]:
import numpy as np
data2=[[1,2,3,4]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

2
(1, 4)
[[1 2 3 4]]


In [ ]:
a=np.array([[0,1,2],[2,3,4]])
a

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
ar=np.zeros((4,4))
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ar=np.ones((3,5))
ar

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr=np.arange(0,20,5)
arr

array([ 0,  5, 10, 15])

In [ ]:
arr=np.random.randint(0,15,(4,4))
arr

array([[12, 10, 10,  5],
       [ 7,  5,  2, 13],
       [ 0, 11, 11, 14],
       [ 6,  5,  4,  9]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr*arr)
print(arr-arr)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np
random_array=np.random.randint(0,10,(4,4))
constant_value=5
mul_array=random_array * constant_value
result_array=mul_array-constant_value
print("original array:\n",random_array)
print("multiplied array:\n",mul_array)
print("resulted array:\n",result_array)

original array:
 [[1 9 8 8]
 [6 9 1 1]
 [1 7 4 8]
 [2 1 3 4]]
multiplied array:
 [[ 5 45 40 40]
 [30 45  5  5]
 [ 5 35 20 40]
 [10  5 15 20]]
resulted array:
 [[ 0 40 35 35]
 [25 40  0  0]
 [ 0 30 15 35]
 [ 5  0 10 15]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,4,7],[2,5,8]])
print(arr)
print(arr2)
print(arr2>arr)

[[1 2 3]
 [4 5 6]]
[[1 4 7]
 [2 5 8]]
[[False  True  True]
 [False False  True]]


In [ ]:
import numpy as np
print('Enter row size:')
r=int(input())
print('Enter coloumn size:')
c=int(input())
arr=np.random.randint(0,50,(r,c))
print(arr)


Enter row size:
3
Enter coloumn size:
3
[[17 34 24]
 [46 31 33]
 [15 22 13]]


In [ ]:
# write a program to understand the GCD of 2 numbers in python using recurrsion
def gcd_fun(x,y):
  if (y==0):
    return x
  else:
    return gcd_fun(y,x%y)
x=int(input("Enter the first number:"))
y=int(input("Enter the second number:"))
num=gcd_fun(x,y)
print("GCD of two numbers is: ",num)

Enter the first number:8
Enter the second number:9
GCD of two numbers is:  1


In [ ]:
import re
arr=[10,20,30,40,50,60,70,80,90]
x=int(input("Enter a number:"))
arr_str=','.join(str(i) for i in arr)
match=re.search(r'\b{}\b'.format(x),arr_str)
if match:
  result=arr_str[:match.start()].count(',')
  print(f"Element {x} is present at index {result}")
else:
  print(f"Element {x} is not present in the array")


Enter a number:60
Element 60 is present at index 5


In [ ]:
def linear_search(list1,n,key):
  for i in range(0,n):
    if(list[i]==key):
      return i
  return -1
list1=[1,3,5,7,9]
key=7
n=len(list1)
res=linear_search(list1,n,key)
if(res==-1):
  print("Element not found")
else:
  print()